<?php

namespace HcsOmot\SocialCalendar\CalendarBundle\Repository;

/**
 * EventTermRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTermRepository extends \Doctrine\ORM\EntityRepository
{
}
