imports:
    - { resource: config_dev.yml }
parameters:
    database_name: social_calendar_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
