services:
#    hcs_omot_social_calendar_calendar.example:
#        class: HcsOmot\SocialCalendar\CalendarBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    create_event_handler:
      class: HcsOmot\SocialCalendar\CalendarBundle\Handler\CreateEventHandler
      arguments:
        - "@doctrine.orm.entity_manager"
      tags:
        - {name: tactician.handler, command: HcsOmot\SocialCalendar\CalendarBundle\Command\CreateEventCommand}

    edit_event_handler:
      class: HcsOmot\SocialCalendar\CalendarBundle\Handler\EditEventHandler
      arguments:
        - "@doctrine.orm.entity_manager"
        - "@event_repository"
      tags:
        - {name: tactician.handler, command: HcsOmot\SocialCalendar\CalendarBundle\Command\EditEventCommand}
    event_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
          - HcsOmot\SocialCalendar\CalendarBundle\Entity\Event