services:
#    hcs_omot_social_calendar_calendar.example:
#        class: HcsOmot\SocialCalendar\CalendarBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    create_event_handler:
      class: HcsOmot\SocialCalendar\CalendarBundle\Handler\CreateEventHandler
      arguments:
        - "@doctrine.orm.entity_manager"
      tags:
        - {name: tactician.handler, command: HcsOmot\SocialCalendar\CalendarBundle\Command\CreateEventCommand}

    edit_event_handler:
      class: HcsOmot\SocialCalendar\CalendarBundle\Handler\EditEventHandler
      arguments:
        - "@doctrine.orm.entity_manager"
      tags:
        - {name: tactician.handler, command: HcsOmot\SocialCalendar\CalendarBundle\Command\EditEventCommand}

    create_event_term:
      class: HcsOmot\SocialCalendar\CalendarBundle\Handler\CreateEventTermHandler
      arguments:
        - "@doctrine.orm.entity_manager"
      tags:
        - {name: tactician.handler, command: HcsOmot\SocialCalendar\CalendarBundle\Command\CreateEventTermCommand}